// -----------------------------------------------------------------------
// Darie-Dragos Mitoiu
// TwitStips (postConstants.js) v1.0.0 11/07/2022
// A web application designed for a personal website
// -----------------------------------------------------------------------

// Declaring constants
const SHAPES_REQUEST = "SHAPES_REQUEST";
const SHAPES_SUCCESS = "SHAPES_SUCCESS";
const SHAPES_FAIL = "SHAPES_FAIL";

const SHAPES_DATA_REQUEST = "SHAPES_DATA_REQUEST";
const SHAPES_DATA_SUCCESS = "SHAPES_DATA_SUCCESS";
const SHAPES_DATA_FAIL = "SHAPES_DATA_FAIL";

const SHAPES_DATA_CONTENT_REQUEST = "SHAPES_DATA_CONTENT_REQUEST";
const SHAPES_DATA_CONTENT_SUCCESS = "SHAPES_DATA_CONTENT_SUCCESS";
const SHAPES_DATA_CONTENT_FAIL = "SHAPES_DATA_CONTENT_FAIL";

const SHAPES_ADD_REQUEST = "SHAPES_ADD_REQUEST";
const SHAPES_ADD_SUCCESS = "SHAPES_ADD_SUCCESS";
const SHAPES_ADD_FAIL = "SHAPES_ADD_FAIL";

const SHAPES_UPDATE_REQUEST = "SHAPES_DELETE_REQUEST";
const SHAPES_UPDATE_SUCCESS = "SHAPES_DELETE_SUCCESS";
const SHAPES_UPDATE_FAIL = "SHAPES_DELETE_FAIL";

const SHAPES_DELETE_REQUEST = "SHAPES_DELETE_REQUEST";
const SHAPES_DELETE_SUCCESS = "SHAPES_DELETE_SUCCESS";
const SHAPES_DELETE_FAIL = "SHAPES_DELETE_FAIL";

export {SHAPES_REQUEST, SHAPES_SUCCESS, SHAPES_FAIL,
    SHAPES_DATA_CONTENT_REQUEST, SHAPES_DATA_CONTENT_SUCCESS, SHAPES_DATA_CONTENT_FAIL,
    SHAPES_DATA_REQUEST, SHAPES_DATA_SUCCESS, SHAPES_DATA_FAIL,
    SHAPES_ADD_REQUEST, SHAPES_ADD_SUCCESS, SHAPES_ADD_FAIL,
    SHAPES_UPDATE_REQUEST, SHAPES_UPDATE_SUCCESS, SHAPES_UPDATE_FAIL,
    SHAPES_DELETE_REQUEST, SHAPES_DELETE_SUCCESS, SHAPES_DELETE_FAIL}